i2c/urls.py
from django.conf.urls import url
from i2c import views

app_name = 'i2c'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^edit_device/(?P<device_address_slug>[0-9]{1,3})/$', views.edit_device, name='edit_device'),
    url(r'^refresh$', views.refresh, name='refresh'),
    url(r'^api/1.0/lighting/(?P<device_address>[0-9]{1,3})/$', views.lighting_details, name='lighting_detailslighting')
]

ourhouse_site/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from main import views
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page,
# if successful at logging in
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/main/'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^main/', include('main.urls')),
    url(r'^lighting/', include('lighting.urls')),
    url(r'^i2c/', include('i2c.urls')),
    url(r'^energy/', include('energy.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),

]

i2c/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Device( models.Model ):
     address = models.IntegerField()
     name = models.CharField(max_length=60)
     description = models.CharField(max_length=200)
     slug = models.SlugField()

     def save(self, *args, **kwargs):
          self.slug = slugify(str(self.address))
          super(Device, self).save(*args, **kwargs)

     def __str__(self):
          return str(self.address) + " " + self.description

    
    

i2c/forms.py
from django import forms
from i2c.models import Device

class DeviceForm(forms.ModelForm):
    address = forms.IntegerField(label='Address',  widget=forms.TextInput(attrs={'id':'address', 'class': 'form-control', 'readonly':'readonly'})) # , help_text="Enter the value for the three bit device address")
    name = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'id':'name', 'class': 'form-control'}))
    description = forms.CharField(max_length=200, label='Description', widget=forms.TextInput(attrs={'id':'description', 'class': 'form-control'})) #, help_text="Enter a description for the device")
 
    class Meta:
        model = Device
        fields=("address", "name", "description", )
        exclude = ('device_type', 'slug',)
        
        
        

i2c/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.http import HttpResponseBadRequest

from i2c.models import Device
from i2c.forms import DeviceForm
from django.contrib.auth.decorators import login_required
## from i2c.i2c_devices import i2c_refresh
from i2c.i2c_lib import i2c_refresh, i2c_lighting_sync
import json

def index( request, new_found=-1 ):

        devices_list = Device.objects.order_by('address')
        context_dict = {'pagetitle': 'Our House','pagename': 'I2C Devices',
                        'titlebar': 'I<sup>2</sup>C Devices',
                        "devices": devices_list}
        if new_found >= 0:
                context_dict["new_found"] = new_found

        return render(request, 'i2c/index.htm', context=context_dict)

@login_required
def edit_device( request, device_address_slug ):
        try:
                device = Device.objects.get(slug=device_address_slug)

                print("DEVICE=" + str(device))
                context_dict = {'device': device}
                
                form = DeviceForm(auto_id=False, initial={'address': device.address, 'name': device.name, 'description': device.description, 'slug': device_address_slug})
                if request.method == 'POST':
                        form = DeviceForm( request.POST, instance=device, auto_id=False)
                        if form.is_valid():
                                device = form.save(commit=False)
                                device.slug = device_address_slug
                                print("SAVING DEVICE=" + str(device))
                                device.save()
                                return index( request )
                        else:
                                print(form.errors)
               
        except Device.DoesNotExist:
                device = None
        context_dict = {'pagetitle': 'Our House','pagename': 'I2C Devices',
                        'titlebar': 'I<sup>2</sup>C Devices',
                        'device_form': form}
        return render(request, 'i2c/edit_device.htm', context_dict)



@login_required
def refresh( request ):
        # TODO - call the system script to run refresh the database
        new_found = i2c_refresh()
        return index ( request, new_found )

def about( request ):
        if request.session.test_cookie_worked():
                print("THE TEST COOKIE WORKED")
                request.session.delete_test_cookie()
        context_dict = {'pagetitle': 'Our House',
                        'pagename' : 'Our Hourse - About'}
        return render(request, 'about.htm', context=context_dict)


@login_required
def lighting_details( request, device_address):
        if request.method == 'GET':
                registers = i2c_lighting_sync( device_address )
                
                return JsonResponse(registers)
        return HttpResponseBadRequest()
        

i2c/templates/i2c/about.htm
{% extends 'base.htm' %}
{% load staticfiles %}


{% block page_title_block %}
    <h1>{{ pagetitle }}</h1>
    <h2>{{ pagename }}</h2>
{% endblock %}

{% block body_block %}
      <div>
        <p>TODO - Resource graphs</p>
      </div>
{% endblock %}

i2c/templates/i2c/edit_device.htm
{% extends 'base.htm' %}
{% load staticfiles %}


{% block page_title_block %}
    <h1>{{ pagetitle }}</h1>
    <h2>{{ pagename }}</h2>
{% endblock %}

{% block body_block %}

   <div class="container">
      <form class="form-horizontal" id="device_form" role="form" method="post" action=".">
         {% csrf_token %}
         <div class="form-group">
            <div class="row">
               <label class="col-sm-2 control-label" for="{{ zone_form.address.id_for_label }}">Address:</label>
               <div class="col-sm-4">
                  {{ device_form.address }}
               </div>
            </div>
         </div>
         <div class="form-group">
            <div class="row">
               <label class="col-sm-2 control-label" for="{{ zone_form.name.id_for_label }}">Name:</label>
               <div class="col-sm-6">
                  {{ device_form.name }}
               </div>
            </div>
         </div>
         <div class="form-group">
            <div class="row">
               <label class="col-sm-2 control-label" for="{{ zone_form.description.id_for_label }}">Description:</label>
               <div class="col-sm-6">
                  {{ device_form.description }}
               </div>
            </div>
         </div>
         <button class="btn btn-md btn-primary" type="submit" value="Update">Update</button>
      </form>
   </div>



{% endblock %}

i2c/templates/i2c/index.htm
{% extends 'base.htm' %}
{% load staticfiles %}

{% block page_title_block %}
    <h1>{{ pagetitle }}</h1>
    <h2>{{ pagename }}</h2>
{% endblock %}

{% block body_block %}
      <div class="container">
        {% if user.is_authenticated %}
          <p>
            <a href="{% url 'i2c:refresh' %}" class="btn btn-sm btn-primary" role="button">Refresh Devices</a>
            {% if new_found != None %}
              {% if new_found == 0 %}
                No new devices were found
              {% else %}
                New devices found: {{new_found}}
              {% endif %}
            {% endif %}
          </p>
        {% endif %}
      </div>
      <div class="container">
        {% if devices %}
          <table class="table table-striped table-bordered" >
            <thead class="thead-inverse">
              <tr>
                <th>Address</th>
                <th>Name</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              {% for device in devices %}
              {% if device.address > 0 %}
                <tr>
                  {% if user.is_authenticated %}
                    <td><a href="{% url 'i2c:edit_device' device.slug %}">{{ device.address }}</a></td>
                  {% else %}
                    <td>{{ device.address }}</td>
                  {% endif %}
                  <td>{{ device.name }}</td>
                  <td>{{ device.description }}</td>
                </tr>
                {% endif %}
              {% endfor %}
            </tbody>  
          </table>
          {% else %}
            <strong>There are no device types present</strong>
        {% endif %}
      </div>
{% endblock %}