energy/urls.py
from django.conf.urls import url
from energy import views

app_name = 'energy'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^usage-graph/summary.png$', views.summary, name="energy-summary"),
    url(r'^usage-graph/resource.png$', views.graph_for_resource, name="energy-resource"),
    url(r'^resource-graph$', views.resource_graph, name="resource_graph_form"),
    url(r'^resource-entry$', views.resource_usage_entry, name="resource_usage_entry"),

]

i2c/urls.py
from django.conf.urls import url
from i2c import views

app_name = 'i2c'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^edit_device/(?P<device_address_slug>[0-9]{1,3})/$', views.edit_device, name='edit_device'),
    url(r'^refresh$', views.refresh, name='refresh'),
    url(r'^api/1.0/lighting/(?P<device_address>[0-9]{1,3})/$', views.lighting_details, name='lighting_detailslighting')
]

ourhouse_site/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from main import views
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page,
# if successful at logging in
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/main/'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^main/', include('main.urls')),
    url(r'^lighting/', include('lighting.urls')),
    url(r'^i2c/', include('i2c.urls')),
    url(r'^energy/', include('energy.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),

]

energy/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django_pandas.managers import DataFrameManager

class Resource( models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Resource, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class ResourceValueFactor( models.Model ):
    resource = models.ForeignKey( Resource )
    start_year = models.IntegerField( blank=True, null=True)
    end_year = models.IntegerField(blank=True, null=True)
    billing_factor = models.DecimalField(max_digits=9, decimal_places=4)
    status_value = models.DecimalField(max_digits=9, decimal_places=4)
    factor = models.DecimalField(max_digits=9, decimal_places=4)

    def __str__(self):
        return "{0} - {1} - {2}: {3}".format(str(self.resource.name), str(self.start_year),
                                       str(self.end_year), str(self.factor))
 

class ResourceEntry( models.Model ):
    resource = models.ForeignKey( Resource )
    time_stamp = models.DateField()
    value_open = models.DecimalField( max_digits=9, decimal_places=4)
    value_close = models.DecimalField( max_digits=9, decimal_places=4)
    # Adjustments are made when there is a meter change, for instance.
    value_adjust = models.DecimalField( max_digits=9, decimal_places=4)
    value_usage = models.DecimalField( max_digits=9, decimal_places=4)
    comment = models.CharField(max_length=200, blank=True, null=True)

    objects = DataFrameManager()


    class Meta:
        verbose_name_plural = 'ResourceEntries'

    def __str__(self):
        return "{0} - {1}: {2}".format(str(self.resource.name),
                                       str(self.time_stamp),
                                       str(self.value_usage))

energy/forms.py
from django import forms
from energy.models import Resource, ResourceEntry

class ResourceGraphForm( forms.Form ):

	## resources = Resource.objects.all()
	

	resource = forms.ModelChoiceField(label="Resource", queryset=None, empty_label=None, widget=forms.RadioSelect(attrs={'class': 'form-control'}))
	start_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	end_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control'}))



class ResourceEntryForm( forms.ModelForm ):
	
	## resources = Resource.objects.all()
	
	resource = forms.ModelChoiceField(label="Resource", queryset=None, empty_label=None, widget=forms.RadioSelect(attrs={'class': 'form-control'}))
	time_stamp = forms.DateField( label="Date", widget=forms.TextInput(attrs={'class': 'form-control'}))
	value_close = forms.DecimalField( label="Reading", max_digits=9, decimal_places=4, widget=forms.TextInput(attrs={'class': 'form-control'}))
	value_adjust = forms.DecimalField( label="Adjustment", max_digits=9, decimal_places=4, initial=0.0, widget=forms.TextInput(attrs={'class': 'form-control'}))
	comment = forms.CharField(label="Comment", max_length=200, required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))


	class Meta:
		model = ResourceEntry
		fields = ("resource", "time_stamp", "value_close", "value_adjust", "comment", )

energy/views.py
from django.shortcuts import render
from energy.plotting import plot_summary
from energy.plotting import plot_for_resource


from energy.forms import ResourceGraphForm, ResourceEntryForm
from energy.models import Resource, ResourceEntry

import datetime

# Create your views here.


def index( request, context_dict=None ):

		if context_dict == None:
				context_dict = {'pagetitle': 'Our House','pagename': 'Energy',
								'titlebar': 'Energy' }
				## resource = "Gas"
				end_date = datetime.date.today()
				start_date = end_date + datetime.timedelta(days = -((365*2.5)))
				
				context_dict["end_date"] = end_date.isoformat()
				context_dict["start_date"] = start_date.isoformat()
				context_dict["resource"] = "3"
		else:
				print("context_dict={0}".format(context_dict))

		print("energy.views: resource={0}, start_date={1}, end_date={2}".format(context_dict["resource"],
																				context_dict["start_date"],
																				context_dict["end_date"]))

		form = ResourceGraphForm( initial={'resource': context_dict["resource"],
										   'start_date':context_dict["start_date"],
										   'end_date':context_dict["end_date"]})
		resources = Resource.objects.all()

		form.fields["resource"].queryset = resources
		form.fields["resource"].initial = resources[0]
		context_dict["resource_graph_form"] = form
		return render(request, 'energy/index.htm', context=context_dict)


def resource_graph( request ):
		print("energy.views.resource_graph BEGIN")
		context_dict = {'pagetitle': 'Our House','pagename': 'Energy',
								'titlebar': 'Energy' }
		if request.method == 'GET':
				print("energy.views.resource_graph: Processing POST")
				form = ResourceGraphForm( request.GET )
				context_dict["resource"] = request.GET["resource"]
				context_dict["start_date"] = request.GET["start_date"]
				context_dict["end_date"] = request.GET["end_date"]
				return index( request , context_dict)

		print("energy.views.resource_graph END")
		return render (request, 'energy/index.htm', context_dict)

		

def about( request ):
		context_dict = {'pagetitle': 'Our House',
						'pagename' : 'Energy - About'}
		return render(request, 'about.htm', context=context_dict)



def summary(request) :
		return plot_summary()


def graph_for_resource(request) :
		
		print("energy.views.graph_for_resource BEGIN")
		resource  = request.GET["resource"]
		start_date = request.GET["start_date"]
		end_date = request.GET["end_date"]

		print("energy.views.graph_for_resource: resource={0}, start_date={1}, end_date={2}".format(
				resource, start_date, end_date))

		resource = Resource.objects.filter(id = resource)[0].name

		## return render (request, 'energy/index.htm', context_dict)
		print("energy.views.graph_for_resource END")
		return plot_for_resource( resource, start_date, end_date)


def resource_usage_entry( request, context_dict = None):
	print("energy.views.resource_usage_entry: BEGIN")
	
	if context_dict == None:
				context_dict = {'pagetitle': 'Our House','pagename': 'Energy',
								'titlebar': 'Resource Entry' }
	resources = Resource.objects.all()
	form = ResourceEntryForm()
	form.fields["resource"].queryset = resources
	form.fields["resource"].initial = resources[0]


	if request.method == 'POST':
		form = ResourceEntryForm(request.POST)
		form.fields["resource"].queryset = resources
		form.fields["resource"].initial = resources[0]


		if form.is_valid():
			resourceEntry = form.save(commit = False)
			
			end_range = resourceEntry.time_stamp
			start_range = end_range + datetime.timedelta(days = -(90))
			print("energy.views: resource={0}, start_date={1}, end_date={2}".format(resourceEntry.resource, start_range, end_range))

			previousEntry = ResourceEntry.objects.filter(resource=resourceEntry.resource, time_stamp__range=[start_range, end_range]).order_by('-time_stamp')[0]
			
			resourceEntry.value_open = previousEntry.value_close
			resourceEntry.value_usage = (resourceEntry.value_close + resourceEntry.value_adjust) - resourceEntry.value_open
			print("Previous(Date={0}, Open={1}, Close={2})".format(previousEntry.time_stamp, previousEntry.value_open, previousEntry.value_close))
			print("New     (Date={0}, Open={1}, Close={2})".format(resourceEntry.time_stamp, resourceEntry.value_open, resourceEntry.value_close))
			resourceEntry.save()
			context_dict = {'pagetitle': 'Our House','pagename': 'Energy',
								'titlebar': 'Energy' }
			end_date = datetime.date.today()
			start_date = end_date + datetime.timedelta(days = -(365*2))
				
			context_dict["end_date"] = end_date.isoformat()
			context_dict["start_date"] = start_date.isoformat()
			context_dict["resource"] = resourceEntry.resource.id
			
			
			return index(request, context_dict=context_dict)
		else:
			print(form.errors)
	context_dict["form"] = form
	print("energy.views.resource_usage_entry: END")
	return render(request, 'energy/resource_entry.htm', context=context_dict)

energy/templates/energy/about.htm
{% extends 'base.htm' %}
{% load staticfiles %}


{% block page_title_block %}
    <h1>{{ pagetitle }}</h1>
    <h2>{{ pagename }}</h2>
{% endblock %}

{% block body_block %}
      <div>
        <p>TODO - Resource graphs</p>
      </div>
{% endblock %}

energy/templates/energy/index.htm
{% extends 'base.htm' %}
{% load staticfiles %}

{% block page_title_block %}
    <h1>{{ pagetitle }}</h1>
{% endblock %}

{% block body_block %}
    <div class="container">
        <form class="form-horizontal" action="{% url 'energy:resource_graph_form' %}" method="GET" 
              id="id_graph_form">
              {% csrf_token %}
            <fieldset>
				<div class="row">
					<div class="col-sm-3">
						<div class="form-group">

							<label class="control-label" for="id_resource">Resource</label>
							{{ resource_graph_form.resource }}
						</div>
					</div>
					<div class="col-sm-4">
						<div class="form-group">
							<label class="control-label" for="id_start_date">Start date</label>
							{{ resource_graph_form.start_date }}
						</div>
					</div>
					<div class="col-sm-4">
						<div class="form-group">
							<label class="control-label" for="id_end_date">End date</label>
							{{ resource_graph_form.end_date }}
						</div>
					</div>
					<div class="col-sm-1">
						<div class="form-group">
							<!-- a href="{% url 'energy:resource_graph_form' %}" class="btn btn-md btn-primary" role="button">Go</a -->
							<label class="control-label" for="id_form_button"></label>
							<input id="id_form_button" class="btn btn-md btn-primary " role="button" type="submit" value="OK" />
						</div>
					</div>
				</div> 
			</fieldset>
        </form>
        <div class="row">
			<div class="col-sm-12 col-sm-push-10">
				<a class="btn btn-md btn-primary" href="{% url 'energy:resource_usage_entry' %}">Enter New</a>
			</div>
        </div>
        <div class="row">
           <div class="col-sm-6">
               <img  class="image-responsive impage-rounded" id="id_resource_graph" src="{% url 'energy:energy-resource' %}?resource={{resource}}&start_date={{start_date}}&end_date={{end_date}}">
           </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script>
	$( function() {
		$( "#id_start_date" ).datepicker({"dateFormat": "yy-mm-dd"});
		$( "#id_end_date" ).datepicker({"dateFormat": "yy-mm-dd"});
		
		
	} );
</script>
{% endblock %}

energy/templates/energy/resource_entry.htm
{% extends 'base.htm' %}
{% load staticfiles %}

{% block page_title_block %}
    <h1>{{ pagetitle }}</h1>
    <h2>{{ pagename }}</h2>
{% endblock %}

{% block body_block %}
	<div class="container">
		<form class="form-horizontal" id="resource_usage_form" role="form" method="post" 
			action="{% url 'energy:resource_usage_entry' %}">
			{% csrf_token %}
			<fieldset>
				<div class="row">
					{% for hidden in form.hidden_fields %}
						{{ hidden }}
					{% endfor %}
					{% for field in form.visible_fields %}
						{{ field.errors }}
						{{ field.help_text }}
						<div class="form-group col-sm-4">
							<label class="control-label col-sm-1" for="{{ zone_form.name.id_for_label }}">{{field.label}}</label>
							{{ field }}
						</div>
					{% endfor %}
				</div>
			</fieldset>
			<input class="btn btn-md btn-primary" type="submit" name="submit" value="Add usage"/>
		</form>
	</div>

{% endblock %}

{% block javascript %}
<script>
	$( function() {
		$( "#id_time_stamp" ).datepicker({"dateFormat": "yy-mm-dd"});
	} );
</script>
{% endblock %}