energy/urls.py
from django.conf.urls import url
from energy import views

app_name = 'energy'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^usage-graph/summary.png$', views.summary, name="energy-summary"),
    url(r'^usage-graph/resource.png$', views.graph_for_resource, name="energy-resource"),
    url(r'^resource-graph$', views.resource_graph, name="resource_graph_form"),
    url(r'^resource-entry$', views.resource_usage_entry, name="resource_usage_entry"),

]

i2c/urls.py
from django.conf.urls import url
from i2c import views

app_name = 'i2c'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^edit_device/(?P<device_address_slug>[0-9]{1,3})/$', views.edit_device, name='edit_device'),
    url(r'^refresh$', views.refresh, name='refresh'),
    url(r'^api/1.0/lighting/(?P<device_address>[0-9]{1,3})/$', views.lighting_details, name='lighting_detailslighting')
]

lighting/urls.py
from django.conf.urls import url
from lighting import views

app_name = 'lighting'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^edit_zone/(?P<zone_slug>[\w\-]+)/$', views.edit_zone, name='edit_zone'),
]

main/urls.py
from django.conf.urls import url, include
from main import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^about$', views.about, name = 'about'),
    url(r'dashboard_refresh', views.dashboard_refresh, name='dashboard_refresh'),
  #  url(r'^login$', views.user_login, name = 'login'),
  #  url(r'^logout$', views.user_logout, name = 'logout'),
  #  url(r'^register$', views.register, name = 'register')
    ]

ourhouse_site/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from main import views
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page,
# if successful at logging in
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/main/'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^main/', include('main.urls')),
    url(r'^lighting/', include('lighting.urls')),
    url(r'^i2c/', include('i2c.urls')),
    url(r'^energy/', include('energy.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),

]

templates/NavbarTemplateforBootstrap.htm
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>{{ pagename }}</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/navbar/navbar.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Our House</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Lighting</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Devices</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Energy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Expenses</a>
          </li>
          <!-- li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My House</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">

              {% if user.is_authenticated %}
                <li>{{user.name}}</li>
                <li><a class="dropdown-item" href="{% url 'auth_logout' %}?next=/main/">Logout</a></li>
              {% else %}
                <li><a class="dropdown-item" href="{% url 'auth_login' %}">Sign in</a></li>
                <li><a class="dropdown-item" href="{% url 'registration_register' %}">Register</a></li>
              {% endif %}

            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    

    <div class="container">
      <div class="jumbotron">
        <div class="col-sm-8 mx-auto">
          {% block body_block %}
          {% endblock %}
        </div>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/NavbarTemplateforBootstrap.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Navbar Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Navbar</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <nav class="navbar navbar-inverse bg-inverse navbar-toggleable-md">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleContainer" aria-controls="navbarsExampleContainer" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Container</a>

        <div class="collapse navbar-collapse" id="navbarsExampleContainer">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
              <div class="dropdown-menu" aria-labelledby="dropdown02">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
          <form class="form-inline my-2 my-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <nav class="navbar navbar-inverse bg-inverse navbar-toggleable-md">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleCenteredNav" aria-controls="navbarsExampleCenteredNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExampleCenteredNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Centered nav only <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <nav class="navbar navbar-light bg-faded rounded navbar-toggleable-md">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#containerNavbar" aria-controls="containerNavbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Navbar</a>

        <div class="collapse navbar-collapse" id="containerNavbar">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
          <form class="form-inline my-2 my-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

      <nav class="navbar navbar-light bg-faded rounded navbar-toggleable-md">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#containerNavbarCenter" aria-controls="containerNavbarCenter" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="containerNavbarCenter">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Centered nav only <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
              <div class="dropdown-menu" aria-labelledby="dropdown05">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <div class="jumbotron">
        <div class="col-sm-8 mx-auto">
          <h1>Navbar examples</h1>
          <p>This example is a quick exercise to illustrate how the navbar and its contents work. Some navbars extend the width of the viewport, others are confined within a <code>.container</code>. For positioning of navbars, checkout the <a href="../navbar-top/">top</a> and <a href="../navbar-top-fixed/">fixed top</a> examples.</p>
          <p>At the smallest breakpoint, the collapse plugin is used to hide the links and show a menu button to toggle the collapsed content.</p>
          <p>
            <a class="btn btn-primary" href="../../components/navbar/" role="button">View navbar docs &raquo;</a>
          </p>
        </div>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/about.htm
{% extends 'base.htm' %}
{% load staticfiles %}


{% block page_title_block %}
    <h1>{{ pagetitle }}</h1>
    <h2>{{ pagename }}</h2>
{% endblock %}

{% block body_block %}
      <div>
        <p>TODO - Resource graphs</p>
      </div>
{% endblock %}

templates/base.htm
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'image/favicon.ico' %}">

    <title>{{ pagename }}</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/navbar/navbar.css" rel="stylesheet">
    {% block localstyles %}{% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-toggleable-sm navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'main:index' %}">Our House</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if pagename == 'Lighting' %}
            <li class="nav-item active" >
          {% else %}
            <li class="nav-item" >
          {% endif %}
            <a class="nav-link" href="{% url 'lighting:index' %}">Lighting</a>
          </li>
          {% if pagename == 'I2C Devices' %}
            <li class="nav-item active">
          {% else %}
            <li class="nav-item">
          {% endif %}
            <a class="nav-link" href="{% url 'i2c:index' %}">Devices</a>
          </li>
          {% if pagename == 'Energy' %}
            <li class="nav-item active">
          {% else %}
            <li class="nav-item">
          {% endif %}
            <a class="nav-link" href="{% url 'energy:index' %}">Energy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Expenses</a>
          </li>
          <!-- li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li -->

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My House</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              {% if user.is_authenticated %}
                <a class="dropdown-item" href="#">{{ user.username }}</a>
                <a class="dropdown-item" href="{% url 'auth_logout' %}?next=/main/">Logout</a>
              {% else %}
                <a class="dropdown-item" href="{% url 'auth_login' %}">Sign in</a>
                <a class="dropdown-item" href="{% url 'registration_register' %}">Register</a>
              {% endif %}
            </div>
          </li>
        </ul>
        <!-- form class="form-inline my-2 my-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form -->
      </div>
    </nav>

    <!-- div class=container>
      <img src="{% static 'image/ourhouse-logo_320_265_g.png' %}">
    </div -->
    

    <!-- div class="container" -->
       <!-- div class="col-sm-12 mx-auto" -->
          {% block body_block %}
          {% endblock %}
       <!-- /div -->
    <!-- /div -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" ></script>
     <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="{% static "channels/js/websocketbridge.js" %}" type="text/javascript"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

templates/index.htm
{% extends 'base.htm' %}
{% load staticfiles %}

{% block page_title_block %}
    <h1>{{ pagetitle }}</h1>
{% endblock %}

{% block body_block %}
      <div class="container">
        <h2>Energy Usage Summary</h2>
        <div class="col-sm-10">
			<img class="image-responsive image-rounded"  id="id_resource_summary_graph"  src="{% url 'energy:energy-summary' %}" >
		</div>
      </div>
{% endblock %}

templates/x_base.htm
<!DOCTYPE HTML>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="utf-8"/>
    <title>
        {{ pagename }} 
    </title>

    <script>
      document.createElement("header");
      document.createElement("nav");
      document.createElement("section");
      document.createElement("aside");
      document.createElement("footer");
    </script>

    <link href="{% static "ourhouse.css" %}" type="text/css" rel="stylesheet" />
    <link href="{%  static "ourhouse_narrow.css" %}" type="text/css" rel="stylesheet" />

</head>

<body>
<div id="wrapper">
    <header>
      {% block page_title_block %}
      {% endblock %}
      {% if user.is_authenticated %}
        {{ user.username }}
      {% else %}
        guest
      {% endif %}
      <div>{{ visits }}</div>
  </header>
  <div id="main">
    <nav>
    <ul>
      <li><a href="{% url 'main:index' %}">Start</a></li>
      <li><a href="lighting.htm">Lighting</a></li>
      <li><a href="{% url 'i2c:index' %}">Devices</a></li>
      <li><a href="#">Energy</a></li>
      <li><a href="#">Expenses</a></li>
      {% if user.is_authenticated %}
        <li><a href="{% url 'auth_logout' %}?next=/main/">Logout</a></li>
      {% else %}
        <li><a href="{% url 'auth_login' %}">Sign in</a></li>
        <li><a href="{% url 'registration_register' %}">Register</a></li>
      {% endif %}
      <li><a href="{% url 'main:about' %}">about</a></li>
    </ul>
  </nav>
  <section>
    {% block body_block %}
    {% endblock %}
  </section>
  <!-- aside>
  </aside -->
</div>
    <footer>
    <a href="../de/index.htm">Deutsch</a>
  </footer>
</div>

</body>

</html>