i2c/urls.py
from django.conf.urls import url
from i2c import views

app_name = 'i2c'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^edit_device/(?P<device_address_slug>[0-9]{1,3})/$', views.edit_device, name='edit_device'),
    url(r'^refresh$', views.refresh, name='refresh'),
    url(r'^api/1.0/lighting/(?P<device_address>[0-9]{1,3})/$', views.lighting_details, name='lighting_detailslighting')
]

main/urls.py
from django.conf.urls import url, include
from main import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^about$', views.about, name = 'about'),
    url(r'dashboard_refresh', views.dashboard_refresh, name='dashboard_refresh'),
  #  url(r'^login$', views.user_login, name = 'login'),
  #  url(r'^logout$', views.user_logout, name = 'logout'),
  #  url(r'^register$', views.register, name = 'register')
    ]

ourhouse_site/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from main import views
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page,
# if successful at logging in
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/main/'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^main/', include('main.urls')),
    url(r'^lighting/', include('lighting.urls')),
    url(r'^i2c/', include('i2c.urls')),
    url(r'^energy/', include('energy.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile( models.Model ):
    user = models.OneToOneField( User )
    picture = models.ImageField( upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.useranme

main/forms.py
from django import forms
from django.contrib.auth.models import User
from main.models import UserProfile

class UserForm( forms.ModelForm ):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture', )
        

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from main.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime

##from i2c.i2c_lib import i2c_get_status
##from i2c.i2c_lib import i2c_get_config

from lighting.models import LightingState
from i2c.models import Device


def get_server_side_cookie(request, cookie, default_val=None):
        val = request.session.get(cookie)
        if not val:
                val = default_val
        return val


def visitor_cookie_handler( request ):
        # Get the number of visits to the site.
        # We use the COOKIES.get() function to obtain theh visits cookie.
        # If the cookie exists, the value returned is cast to an integer.
        # If the cookie doesn't exist, then the default value of 1 is used.
        visits = int(get_server_side_cookie(request, 'visits', '1'))
        last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
        last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

        # If it's been more than a day since the last visit...
        if (datetime.now() - last_visit_time).days > 0:
                visits = visits + 1
                # Update the lst viist cookie now that we have updated the count
                request.session['last_visit'] = str(datetime.now())
        else:
                visists = 1
                # Set the last visit cookie
                request.session['last_visit'] = last_visit_cookie

        # Update/Set the visit cookie
        request.session['visits'] = visits





def index( request ):
        request.session.set_test_cookie()
        context_dict = {'pagetitle': 'Our House',
                        'pagename' : 'Our Hourse - Start'}

        # Call the function to handle the cookies
        visitor_cookie_handler(request)
        context_dict['visits'] = request.session['visits']
        response = render(request, 'index.htm', context=context_dict)

        return response

def dashboard( request , status_dict=None):
        if status_dict == None:
                print("Calling the dashboard refresh for the first time")
                return dashboard_refresh( request )
        print("STATUS_DICT=" + str(status_dict))
        response = render(request, 'main/dashboard.htm', context=status_dict)
        return response

def dashboard_refresh( request ):
##        status_int = i2c_get_status( 32 )
##        config_int = i2c_get_config( 32 )
        device = Device.objects.get(name="Lighting")
        history = LightingState.objects.get(device = device)
        status_int = history.status
        config_int = history.config
        print("status {0:08b}, config {1:08b}".format(status_int, config_int))
        status_dict = {"UG_State": "DISABLED", "EG_State": "DISABLED", "OG_State": "DISABLED" }
        
        if config_int & 0b00010000 >= 1:
                print("Setting UG to OFF")
                status_dict["UG_State"]="OFF"
        if config_int & 0b00100000 >= 1:
                print("Setting EG to OFF")
                status_dict["EG_State"]="OFF"
        if config_int & 0b01000000 >= 1:
                print("Setting OG to OFF")
                status_dict["OG_State"]="OFF"
           
        if status_int & 0b00000001 >= 1:
                print("Setting UG to ON")
                status_dict["UG_State"] = "ON"
        if status_int & 0b00000010 >= 1:
                print("Setting EG to ON")
                status_dict["EG_State"] = "ON"
        if status_int & 0b00000100 >= 1:
                print("Setting OG to ON")
                status_dict["OG_State"] = "ON"

        print("status_refresh status_dict=" + str(status_dict))
                
        return dashboard( request, status_dict=status_dict )


def about( request ):
        if request.session.test_cookie_worked():
                print("THE TEST COOKIE WORKED")
                request.session.delete_test_cookie()
        context_dict = {'pagetitle': 'Our House',
                        'pagename' : 'Our Hourse - About'}
        return render(request, 'about.htm', context=context_dict)


##def register( request ):
##        # A boolean value for telling the template
##        # whether the registration was successful.
##        # Set to False initially. Code changes value to
##        # True when registration succeeds.
##        registered = False
##
##        # If it's a HTTP POST, we're interested in processing from data
##        if request.method == 'POST':
##                # Attempt to grab information from the raw form information.
##                # Note that we make use of both UserForm and UserProfileForm.
##                user_form = UserForm(data=request.POST)
##                profile_form = UserProfileForm(data=request.POST)
##
##                # If the two forms are valid...
##                if user_form.is_valid() and profile_form.is_valid():
##                        # Save the user's form data to the database.
##                        user = user_form.save()
##
##                        # Now we hash the password with the set_password method
##                        # Once hashed, we can u pdate the user object
##                        user.set_password(user.password)
##                        user.save()
##
##                        # Now sort out the UserProfile instance.
##                        # Since we need to set the user attribute ourselves
##                        # we set commit=False. This delays saving the model
##                        # until we're ready to avoid integrity problems.
##                        profile = profile_form.save(commit=False)
##                        profile.user = user
##
##                        # Did teh user provide a profile picture?
##                        # If so, we need to get it from the input Form and
##                        # put it in the UserProfile model.
##                        if 'picture' in request.FILES:
##                                profile.picture = request.FILES['picture']
##
##                        # Now we save the UserProfile model instance.
##                        profile.save()
##
##                        # Update our variable to indicate that the tempalte
##                        # registration was successful
##                        registered = True
##
##                else:
##                        # Invalid form or forms - mistakes or something else?
##                        # Print the problem to the terminal
##                        print(user_form.errors, profile_form.errors)
##        else:
##                # Not a HTTP POST, so we render out form using two ModelForm instances.
##                # These forms will be blank, ready for user input.
##                user_form = UserForm()
##                profile_form = UserProfileForm()
##
##        # Render the template depending on the context.
##        return render(request, 'register.htm',
##                      {'user_form': user_form,
##                       'profile_form': profile_form,
##                       'registered': registered})
##
##
##def user_login( request ):
##        # If the requst is a HTTP POST, try to pull out the relevant information
##        if request.method == 'POST':
##                # Gather the username and passwrod provided by the user.
##                # This information is obtained from the login form.
##                # We use request.POST.get('<variable>') as opposed
##                # to requst.POST['<variable>'], because the
##                # request.POST.get('<variable>') returns None if the
##                # value does not exist, while request.POST['<variable>']
##                # will raise a KeyError exception.
##                username = request.POST.get('username')
##                password = request.POST.get('password')
##
##                # Use Django's machinery to attempt to see if the username/password
##                # combination is valid - a User object is returned if it is.
##
##                user = authenticate(username=username, password=password)
##
##                # If we have a User object, the details are correct.
##                # If None (Python's way of representing the absense of a value), no user
##                # with matchin credentials was found.
##                if user:
##                        # Is the account active? It could have been disabled
##                        if user.is_active:
##                                # If teh account is valid and active, we can log the use in.
##                                # We'll send the user back to the homepage.
##                                login(request, user)
##                                return HttpResponseRedirect(reverse('index'))
##                        else:
##                                # An inactive acctoun was used - no logging in
##                                return HttpResponse("Your Our House account is disabled")
##                else:
##                        # Bad login details were provided. So we can't log the user in
##                        print("Invalid login details: {0}, {1}".format(username, password))
##                        # return HttpResponse("Invalid login details")
##                        return render( request, 'login.htm', {'form_error': 'Invalid login details'})
##        # The request is not a HTTP POST, so display the login form.
##        # This scenario would most likely be a HTTP GET.
##        else:
##                # No context variables to pass to the template system, hence the
##                # blank dictionary object
##                return render( request, 'login.htm', {'form_error': ''})
##        
##                

main/templates/main/dashboard.htm
  
{% extends 'base.htm' %}
{% load staticfiles %}

{% block page_title_block %}
   <h1>{{ pagetitle }}</h1>
{% endblock %}

{% block body_block %}
    <div >
    <div><img src="{% static "main/image/gabel.png" %}"/></div>

    <div>
    {% if OG_State == "ON" %}
    <img id="og_img" src="{% static "main/image/Level-Illuminated.png" %}"/>
    {% elif OG_State == "OFF" %}
    <img id="og_img" src="{% static "main/image/Level-Enabled.png" %}"/>
    {% elif OG_State == "DISABLED" %}
    <img id="og_img" src="{% static "main/image/Level-Disabled.png" %}"/>
    {% endif %}
    </div>

    <div>
    {% if EG_State == "ON" %}
    <img id="eg_img" src="{% static "main/image/Level-Illuminated.png" %}"/>
    {% elif EG_State == "OFF" %}
    <img id="eg_img" src="{% static "main/image/Level-Enabled.png" %}"/>
    {% elif EG_State == "DISABLED" %}
    <img id="eg_img" src="{% static "main/image/Level-Disabled.png" %}"/>
    {% endif %}
    </div>

    <div>
    {% if UG_State == "ON" %}
    <img id="ug_img" src="{% static "main/image/Level-Illuminated.png" %}"/>
    {% elif UG_State == "OFF" %}
    <img id="ug_img" src="{% static "main/image/Level-Enabled.png" %}"/>
    {% elif UG_State == "DISABLED" %}
    <img id="ug_img" src="{% static "main/image/Level-Disabled.png" %}"/>
    {% endif %}
    </div>

  </div>
  <br/>
  <div id="show-data"></div>
  <div><a href="#" id="get-data" class="btn btn-sm btn-primary" >Get Details</a></div>
  <div><a href="{% url 'main:dashboard_refresh' %}" id="get-data" class="btn btn-sm btn-primary" role="button" >Get Details</a></div>
{% endblock %}


{% block javascript %}
  <script>
     $(function () {
        var ws_path = "/stream/";
	console.log("Connecting to  + ws_path")

    	var webSocketBridge = new channels.WebSocketBridge();
	webSocketBridge.connect(ws_path);
	webSocketBridge.listen();
	webSocketBridge.demultiplex('tl2c_state', function(payload, streamName) {
           if (payload.action == "update" || payload.action == "create" ) {
              data = payload.data
              console.log("data: " + payload.data + " " );
              status = payload.data.status;
              console.log("STATUS=" + (status >>> 0).toString(2))
              if ((status & 0b000001) > 0) {
                 console.log("UG is ON!")
                 $('#ug_img').attr('src',"{% static "main/image/Level-Illuminated.png" %}");
              } else {
                 console.log("UG is OFF!")
                 $('#ug_img').attr('src',"{% static "main/image/Level-Enabled.png" %}");
              }
              if ((status & 0b000010) > 0) {
                 console.log("EG is ON!")
                 $('#eg_img').attr('src',"{% static "main/image/Level-Illuminated.png" %}");
              } else {
                 console.log("EG is OFF!")
                 $('#eg_img').attr('src',"{% static "main/image/Level-Enabled.png" %}");
              }
              if ((status & 0b000100) > 0) {
                 console.log("OG is ON!")
                 $('#og_img').attr('src',"{% static "main/image/Level-Illuminated.png" %}");
              } else {
                 console.log("OG is OFF!")
                 $('#og_img').attr('src',"{% static "main/image/Level-Enabled.png" %}");
              }
              
           }
           
	});

        webSocketBridge.socket.onopen = function() { 
           console.log("Connected to notification socket"); 
        }
        webSocketBridge.socket.onclose = function() { 
           console.log("Disconnected to notification socket"); 
        }
	console.log("Finished setting up the websocket")

/*    });

  $(document).ready(function () {
*/

    $('#get-data').click(function () {

      $.getJSON('http://home-pi:8000/i2c/api/1.0/lighting/32/', function (data) {
        console.log(data);

        var result = '<ul>';
        result = result.concat('<li>Status ');
        result = result.concat(("00000000"+data.status.toString(2)).substr(-8))
        result = result.concat('</li><li>Config ');
        result = result.concat(("00000000"+data.config.toString(2)).substr(-8))
        result = result.concat('</li><li>Lower level delay ');
        result = result.concat(data.UG_on_delay)
        result = result.concat('</li><li>Ground level delay ');
        result = result.concat(data.EG_on_delay)
        result = result.concat('</li><li>Upper level delay ');
        result = result.concat(data.OG_on_delay)
        result = result.concat('</li><li>Firmware ');
        result = result.concat(data.firmware)
        result = result.concat('</li>');
        result = result.concat('</ul>');
        console.log(result);
        $('#show-data').html(result);
      });
    });



  });


  </script>
{% endblock %}